### ISSUE TITLE
How to use the client

### ISSUE THREAD

**Issue by VinceTheSImp** [M5rian/Shilu#1]
Bro how do I make this run ???????? :)))))))))

**Comment by m5rian** [comment]
That's a good question… I actually don't know how to add this to your Minecraft launcher, I haven't figured that out yet. But you can use the decompile workspace gradle task to setup the project. Then you can run the ShiluTweaker class to start the client.

**Comment by m5rian** [comment]
Did it work for you?

**Comment by m5rian** [comment]
Got fixed with 0cfde82446d9684d8941b86c0210cc15c156c0f1
